.execute database script <|
//
// ingest data
//
.ingest async into table Timeseries (
    h'https://trendersampledata.blob.core.windows.net/data/Timeseries_1_10fe6ab36af04132af3d6d4a5e306144.csv.gz',
    h'https://trendersampledata.blob.core.windows.net/data/Timeseries_1_d1ca391123df4599879267d7f4c959d2.csv.gz',
    h'https://trendersampledata.blob.core.windows.net/data/Timeseries_2_221db6e218bf4b08939db9fce258b594.csv.gz',
    h'https://trendersampledata.blob.core.windows.net/data/Timeseries_2_23a8b7c600ca4a62b213b061d45ece3b.csv.gz'
)
//
.ingest async into table TimeseriesMetadata (
    h'https://trendersampledata.blob.core.windows.net/data/TimeseriesIdMapping_1_28aa6aeabe7c4451b66d9d30cb02c3af.csv.gz'
)
//
.ingest async into table TimeseriesHierarchy (
    h'https://trendersampledata.blob.core.windows.net/data/Hierarchy_1_8c8a328f528949688e0b524deaf1332b.csv.gz'
)