name:  Build and deploy on prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      actions: write
      contents: write
      deployments: write
      security-events: write
      packages: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.5.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
    - run: npm ci --legacy-peer-deps
    - run: npm run build
    - run: npm run prepare-samples
    - run: npm run post-build
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: "./dist/package.json"
    - run: git push
    