name:  Build and deploy on prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run prepare-samples

    - name: Azure Static Website Deploy
      uses: feeloor/azure-static-website-deploy@v0.1.0
      env:
        # The name of the directory you want to upload
        SOURCE_DIR: "./pages/examples"
        # Your Azure Client ID -> create sp with id and secret -> add the sp as contributor to the storage
        AZURE_CLIENT_ID: "${{secrets.CLIENT_ID}}"
        # Your Azure TENANT ID
        AZURE_TENANT_ID: "72f988bf-86f1-41af-91ab-2d7cd011db47"
        # Your Azure Secret
        AZURE_SECRET: "${{secrets.SECRET_ID}}"
        # Your Azure Subscription ID
        AZURE_SUBSCRIPTION_ID: "${{secrets.SUBSCRIPTION_ID}}"
        # Your Azure Storage Account Name
        AZURE_STORAGE_ACCOUNT_NAME: "kustotrender"
        # The index document that you specify when you enable static website hosting, appears when users open the site and dont specify a specific file.
        AZURE_INDEX_DOCUMENT_NAME:  "index.html"