name:  Unnpublish version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to remove'
        required: true
        default: '0.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      actions: write
      contents: write
      deployments: write
      security-events: write
      packages: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Deprecate version
        run: npm deprecate azure-kusto-trender@0.0.19 "Superceded by version 0.0.20"
